x-common-env: &common-env
  env_file:
    - .env

services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: mango-mcp
    image: mango-mcp
    <<: *common-env
    ports:
      - "${MCP_PORT}:${MCP_PORT}"

  mango-build-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: mango-agent
      args:
        EMBEDDING_MODEL: ${EMBEDDING_MODEL}
    image: mango-agent 
    command: ["true"]

  trainer:
    image: mango-agent
    depends_on:
      - mango-build-agent
    command: ["python3", "train_validators.py"]
    <<: *common-env
    volumes:
      - ./models:${TRAINED_MODELS_PATH}

  ce:
    image: mango-agent
    depends_on:
      - mango-build-agent
    <<: *common-env
    environment:
      SERVICE_MODE: ce
      SERVICE_PORT: ${CE_PORT}
    ports:
      - "${CE_PORT}:${CE_PORT}"
    deploy:
      resources:
        limits:
          memory: 1.5g

  business-agent:
    image: mango-agent
    depends_on:
      - mango-build-agent
    <<: *common-env
    environment:
      SERVICE_MODE: agent
      AGENT_NAME: BusinessAgent
      SERVICE_PORT: ${BUSINESS_AGENT_PORT}
    ports:
      - "${BUSINESS_AGENT_PORT}:${BUSINESS_AGENT_PORT}"
    volumes:
      - ./models:${TRAINED_MODELS_PATH}
    deploy:
      resources:
        limits:
          memory: 1.5g

  customers-agent:
    image: mango-agent
    depends_on:
      - mango-build-agent
    <<: *common-env
    environment:
      SERVICE_MODE: agent
      AGENT_NAME: CustomerServiceAgent
      SERVICE_PORT: ${CUSTOMERS_AGENT_PORT}
    ports:
      - "${CUSTOMERS_AGENT_PORT}:${CUSTOMERS_AGENT_PORT}"
    volumes:
      - ./models:${TRAINED_MODELS_PATH}
    deploy:
      resources:
        limits:
          memory: 1.5g
  
  hr-agent:
    image: mango-agent
    depends_on:
      - mango-build-agent
    <<: *common-env
    environment:
      SERVICE_MODE: agent
      AGENT_NAME: HRAgent
      SERVICE_PORT: ${HR_AGENT_PORT}
    ports:
      - "${HR_AGENT_PORT}:${HR_AGENT_PORT}"
    volumes:
      - ./models:${TRAINED_MODELS_PATH}
    deploy:
      resources:
        limits:
          memory: 1.5g